# 4. Numpy

## 4.2 넘파이 기초

numpy에서 가장 기본이 되는 데이터 타입은 nd(N-dimensional)array. array.
ndarray 데이터 타입이 보유한 속성들은 아래와 같습니다.

- ndarray.ndim
- ndarray.shape
- ndarray.size : 원소 개수
- ndarray.dtype 
- ndarray.itemsize : 원소의 바이트 크기
- ndarray.data : 배열의 데이터

In [3]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype

dtype('int64')

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

## 4.3 Numpy 인덱싱/연산

리스트로 만드는 array에 비해 괄호가 적게 사용되고, 인덱싱하기에 더욱 빠르고 용이합니다

In [9]:
b = np.arange(20).reshape(5,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [10]:
b[2,3]

np.int64(11)

In [11]:
b[0:5,1]

array([ 1,  5,  9, 13, 17])

In [12]:
b[:,1]

array([ 1,  5,  9, 13, 17])

In [13]:
b[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

조건문을 통해서도 인식이 가능합니다.
-> Logic -> Boolean array 형성 후 적용

In [14]:
c = a > 4
print(c)
print(a[c])

[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 5  6  7  8  9 10 11 12 13 14]


사칙연산도 가능합니다. 크기 같은 두 개의 array 간 사치연산을 실시하면 element-wise 연산이 실행됩니다. 또한 제곱 연산이나 기타 연산도 element-wise하게 적용됩니다.

In [15]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b
print(c)

print(b**2)

print(b*10)

[20 29 38 47]
[0 1 4 9]
[ 0 10 20 30]


array 간 * 연산을 진행하면, element-wst한 곱셈이 실행됩니다. 행렬곱은 dot()함수를 사용해야 합니다.

In [16]:
A = np.array([[1,1],
             [0,1]])
B = np.array([[2,0],
              [3,4]])
print(A * B)
print(np.dot(A,B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


4.4 Numpy 함수

In [21]:
rg = np.random.default_rng(1)
a = rg.random((2,3))
print(a)

print(f'a.sum : {a.sum()}')
print(f'a.min : {a.min()}')
print(f'a.max : {a.max()}')

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
a.sum : 3.290252281866131
a.min : 0.14415961271963373
a.max : 0.9504636963259353


In [22]:
b = np.arange(12).reshape(3,4)

print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
b.sum(axis = 0)

array([12, 15, 18, 21])

In [24]:
b.min(axis = 1)

array([0, 4, 8])

In [25]:
b.cumsum(axis = 1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

그 외에 numpy의 주요함수들 요약

- exp, log, expm1, log1p : 지수함수 또는 로그함수 사용해 숫자 변환
- sqrt, square, abs : 루트, 제곱, 절대값 산출
- mean, median, var, std : 평균, 중앙값, 분산, 표준편차 산출
- sin, cos
- corrcoef
- concatenate, vstack, hstack
- reshape

선형회귀, 로지스틱 회귀 부분은 생략